### ISSUE TITLE
Delete an email

### ISSUE THREAD

**Issue by dhana555std** [alexandrucancescu/node-mailinator-inbox#1]
Hi team,
               Is there a way to delete the email from the inbox?
Regards
Dhana

**Comment by alexandrucancescu** [comment]
Mailinator allows to delete emails from the temporary inbox, but I did not implement it in this package.

**Comment by haideralii** [comment]
@alexandrucancescu 
unable to read messages from malinator
when trying to get all emails from specific email then empty list displays
const firstEmail = inbox.getEmailsFrom("example@mail.com");
response
[]
and when we use await then it throws an error
SyntaxError: await is only valid in async functions and the top level bodies of modules
