### ISSUE TITLE
Inbox.refresh() throws an Error "Index request returned no cookie"

### ISSUE THREAD

**Issue by lnikod4s** [alexandrucancescu/node-mailinator-inbox#2]
Hey there,

I have a custom implementation of MailinatorService which should wait and get the latest email in a public mailinator inbox. Currently, an error is thrown `"Index request returned no cookie"` every time I'm trying to call Inbox.refresh(). Here is a sample code of how exactly Inbox.refresh() is used:

```
private async getLatestEmail(): Promise<Email> {
    await this.inbox.refresh();
    const latestEmailHeader = this.inbox.emailHeaders[this.inbox.emailHeaders.length - 1];
    const latestEmail = await this.inbox.getEmail(latestEmailHeader.id);

    return latestEmail;
}
```

Any suggestions?

**Comment by ghost** [comment]
@lnikod4s @alexandrucancescu 
Getting the same error, did you manage to solve it?

```
Error: Index request returned no cookie
at Inbox.getCookies (/home/thiagoscodeler/test/node_modules/mailinator-inbox/dist/Inbox.js:143:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Inbox.refresh (/home/thiagoscodeler/test/node_modules/mailinator-inbox/dist/Inbox.js:15:9)
at async World.<anonymous> (/home/thiagoscodeler/test/features/step_definitions/login_steps.js:29:5)
```

Code example:
```
When('Test Login', { timeout: 120000 }, async (role) => {
      //Access the inbox
      const inbox = new Inbox(envs[role].userEmail);
      await inbox.refresh();
      const futureEmails = await inbox.waitForEmailsFrom("test@.com", 90000);
  });
```

**Comment by lnikod4s** [comment]
@ThiagoScodeler Unfortunately not. I've decided to replace this package with the official one: 
https://github.com/manybrain/mailinator-javascript-client

**Comment by ghost** [comment]
ok @lnikod4s thank you for replying. I also saw this package but it requires api key.

**Comment by lnikod4s** [comment]
@ThiagoScodeler You need to request a Mailinator Verified Pro subscription (free) in order to acquire an API key. Cheers!

**Comment by alexandrucancescu** [comment]
Hi, sorry for the late response. Unfortunately mailinator has changed their API and to make this package able to retrieve their mails again I have to re examine their API and that can take a lot of time. If in the future I have the time needed and update the package I will let you know in this thread.

@lnikod4s The package you refer to need a subscription from mailinator. This package accesses their public/free inboxes.
